name: Deno

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        # Test for latest stable and canary deno versions
        deno-version: [vx.x.x, canary]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1.1.4
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Check typings
        run: deno check main.ts

      - name: Check formatting
        run: deno fmt --check

      - name: Check linting
        run: deno lint

      - name: Run tests
        run: deno test

      - name: Run dry publish
        run: deno publish --dry-run

      - name: Check license headers
        run: |
          deno run -A --no-check https://deno.land/x/anzu@1.0.2/src/cli.ts \
           -i ./ "/.+\.ts/" \
           -e "deps.ts" \
           -l "// Copyright 2024 Im-Beast. All rights reserved. MIT license."
