name: Node.js

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [21.x, 22.x]

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Prepare environment
        # TODO: Update crayon version after stable release
        run: |
          echo '{ "type": "module" }' > package.json && \
          npx jsr add @crayon/crayon@4.0.0-alpha.3 @cross/test @std/assert

      - name: Run tests
        run: |
          npx --yes tsx --test **/*.test.ts && \
          NO_COLOR=1 npx --yes tsx --test **/*.test.ts
