name: Node.js

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [18.x, 21.x]

    steps:
      - uses: actions/checkout@v3
      # TODO: Update crayon version after stable release
      - run: npx jsr add @crayon/crayon@4.0.0-alpha.2 @cross/test @std/assert
      - run: 'echo ''{ "type": "module" }'' > package.json' # Needed for tsx to work
      - run: npx --yes tsx --test *.test.ts
